config/routes.rb
Rails.application.routes.draw do

  root to: "movies#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'movies/top' => 'movies#top'
  get 'movies/recent' => 'movies#recent'

  resources :movies, only: [:show, :index] do
    resources :ratings, only: [:create, :update]
    resources :reviews, except: [:destroy]
  end

  resources :categories, only: [:index, :show]

  resources :reviews, only: [:show, :index] do
    resources :likes, only: [:create]
  end

  resources :search, only: [:index]

  namespace :admin do
    resources :users
    resources :categories
    resources :movies
    resources :movie_categories
    resources :ratings
    resources :reviews
    resources :likes

    root to: "users#index"
  end

end

app/controllers/admin/movies_controller.rb
module Admin
  class MoviesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Movie.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Movie.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show]
  def index
  	# Number of categories to report on.
  	@NUM_CATS = 3

  	# Number of movies / category
  	@NUM_MOVIES = 6

    @new_movies = Movie.new_releases.limit(15)
    @top_movies = Movie.critically_acclaimed.limit(15)
    top_drama = Category.find_by(name: 'Drama')
    @top_drama = top_drama.movies.limit(15)
    top_action = Category.find_by(name: 'Action')
    @top_action = top_action.movies.limit(15)
    top_comedy = Category.find_by(name: 'Comedy')
    @top_comedy = top_comedy.movies.limit(15)
  	# Get random categories and populate with movies
  	#rand_cats = Category.order("RAND()").first(NUM_CATS)
  	#trending_movies = {}
  	#rand_cats.each do |cat|
  	#	trending_movies[cat] = []
  	#	trending_movies << Movie.order()
  	#end
    # @comedy = Category.find_by(name: 'Comedy')
    @romance = Category.find(9)
    # @drama = Category.find_by(name: 'Drama')
    # @action = Category.find_by(name: 'Action')
  end

  def show
    @reviews = @movie.reviews
    @rating = Rating.find_by(user: current_user, movie: @movie)
    @rating = Rating.new(value: 0) unless @rating
  end

  def top
    @movies = Movie.critically_acclaimed.limit(15)
    render 'movies/top'
  end

  def recent
    @movies = Movie.new_releases.limit(15)
    render 'movies/recent'
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  def display_critic_rating_average_for(movie)
    number_with_precision(movie.ratings.critic_ratings.average(:value), precision: 1) || 'No '
  end

  def display_user_rating_average_for(movie)
    number_with_precision(movie.ratings.user_ratings.average(:value), precision: 1) || 'No '
  end
end

app/views/movies/_carousel.html.erb
<% if movies.present? %>
  <div class="owl-carousel owl-theme">
    <% movies.each do |movie| %>
      <div>
      <%= link_to movie do %>
        <%= image_tag movie.image_url %>
      <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="movie-content">
  <section class="poster-show">
    <a href="<%= movie_path(movie) %>">
      <%= image_tag movie.image_url %>
    </a>
  </section>

  <section class="movie-info">
    <ul class="review-average">
      <li class="line"><%= display_critic_rating_average_for movie %> Critic Rating</li>
      <li><%= display_user_rating_average_for movie %> User Rating</li>
    </ul>

    <ul class="movie-summary">
      <li class="title"><%= movie.title %></li>
      <li class="synopsis"><%= movie.synopsis %></li>
    </ul>

    <ul class="movie-data">
      <li class="line rating"><%= movie.mpaa_rating %></li>
      <li class="line"><%= movie.runtime %> minutes</li>
      <li class="line"><%= movie.categories.first.name %></li>
      <% if movie.release_date %>
        <li><%= movie.release_date.strftime("%d %B %Y") %></li>
      <% end %>
    </ul>

    <ul class="movie-links">
      <li>Watch Trailer</li>
      <li>Visit Website</li>
    </ul>
  </section>
</div>

app/views/movies/index.html.erb
<div class="index-content">
  <nav>
    <ul class="index-nav">
      <li>
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
      </li>
      <li class="logo-name"><h1>FRESH CABBAGE</h1></li>
    </ul>
  </nav>

  <section class="index-banner new-releases">
    <p>New Releases</p>
    <%= render 'movies/carousel', movies: @new_movies %>
  </section>

  <section class="index-banner top-critic">
    <p>Top Critic This Week</p>
     <%= render 'movies/carousel', movies: @top_movies %>
  </section>

  <section class="index-banner best-drama">
    <p>Best in Drama</p>
    <%= render 'movies/carousel', movies: @top_drama %>
  </section>

  <section class="index-banner best-action">
    <p>Best in Action</p>
    <%= render 'movies/carousel', movies: @top_action %>
  </section>
  <section class="index-banner best-comedy">
    <p>Best in Comedy</p>
    <%= render 'movies/carousel', movies: @top_comedy %>
  </section>
</div>

app/views/movies/recent.html.erb
<%= render @movies %>

app/views/movies/show.html.erb
<%= render @movie %>

<div class="review-header">
  <section>
    <h1><%= link_to "USER REVIEWS", [@movie, :reviews] %></h1>
  </section>
  <section>
    <h1><%= link_to "CRITIC REVIEWS", [@movie, :reviews] %></h1>
  </section>
</div>

<div class="review-content">
  <section class="review critic">
    <% @reviews.each do |review| %>
    <ul>
      <% if review.reviewer.critic? %>
      <li>Author: <%= review.reviewer.username %></li>
      <li><%= link_to truncate(review.body, length: 30), [@movie, review] %></li>
      <%= render partial:'likes/counter', :locals => {:review => review} %>
      <span class='like-counter'>
      <%= link_to "Like", review_likes_path(review), { method: :post, :review_id => review.id, class: "like-link" } %>
      </span><br>
      <% end %>
    </ul>
    <% end %>
  </section>


  <section class="review user">
    <% @reviews.each do |review| %>
    <ul>
      <% if review.reviewer.user? %>
      <li>Author: <%= review.reviewer.username %></li>
      <li><%= link_to truncate(review.body, length: 30), [@movie, review] %></li>
      <%= render partial:'likes/counter', locals: {count: @count} %>
      <span class='like-counter'>
      <%= link_to "Like", review_likes_path(review), { method: :post, :review_id => review.id, class: "like-link" } %>
      </span><br>
      <% end %>
    </ul>
    <% end %>
  </section>
</div>

<div id="rating-form">
  <ul>
    <li><%= render 'ratings/form' %></li>
    <li><%= link_to "Write a Review", new_movie_review_path(@movie) %></li>
  </ul>
</div>


<!--  <li><!-- %= link_to "truncate(review.body, length: 30)", review %></li> -->

app/views/movies/top.html.erb
<%= render @movies %>