config/routes.rb
Rails.application.routes.draw do

  root to: "movies#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'movies/top' => 'movies#top'
  get 'movies/recent' => 'movies#recent'

  resources :movies, only: [:show, :index] do
    resources :ratings, only: [:create, :update]
    resources :reviews, except: [:destroy]
  end

  resources :categories, only: [:index, :show]

  resources :reviews, only: [:show, :index] do
    resources :likes, only: [:create]
  end

  resources :search, only: [:index]

  namespace :admin do
    resources :users
    resources :categories
    resources :movies
    resources :movie_categories
    resources :ratings
    resources :reviews
    resources :likes

    root to: "users#index"
  end

end

app/controllers/admin/reviews_controller.rb
module Admin
  class ReviewsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Review.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Review.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show]
  before_action :set_movie, only: [:index]

  def index
    @reviews = @movie.reviews
  end

  def show
  end

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.reviewer = current_user
    @review.movie = @movie

    redirect_to root_path unless @review.reviewer == current_user

    if params[:commit] == "publish"
      @review.published_on = DateTime.now
    end

    if @review.save
      redirect_to movie_review_path(@movie, @review)
    else
      render 'new'
    end
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])

    redirect_to root_path unless @review.reviewer == current_user
  end

  def update
    @review = Review.find(params[:id])
    @movie = Movie.find(params[:movie_id])

    redirect_to root_path unless @review.reviewer == current_user

    if params[:commit] == "publish"
      @review.published_on = DateTime.now
    end

    if @review.update(review_params)
      redirect_to movie_review_path(@movie, @review)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:body)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/views/reviews/edit.html.erb
<div class="review-content">
  <h2>Edit Review</h2>

  <%= form_for [@movie, @review] do |f| %>
    <%= f.text_area :body %>
    <%= f.submit :publish %>
    <%= f.submit :submit %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<div class="review-content">
  <% @reviews.each do |review| %>
    <ul>
      <li>
      <%= link_to truncate(review.body, length: 35), [@movie, review] %>
      </li>

    </ul>
  <% end %>
<div>

app/views/reviews/new.html.erb
<div class="review-content">
  <h2>New Review</h2>

  <%= form_for [@movie, @review] do |f| %>
    <%= f.text_area :body %>
    <%= f.submit :publish %>
    <%= f.submit :submit %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class="review-content">
  <ul>
    <li>Author: <%= @review.reviewer.username %></li>
    <li><%= @review.body %></li>
    <li>Published? = <%= !@review.published_on.nil? %></li>

    <% if @review.reviewer == current_user %>
    <li><%= link_to 'Edit review', edit_movie_review_path(@review.movie, @review) %></li>
    <% end %>
  </ul>
</div>