config/routes.rb
Rails.application.routes.draw do

  root to: "movies#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'movies/top' => 'movies#top'
  get 'movies/recent' => 'movies#recent'

  resources :movies, only: [:show, :index] do
    resources :ratings, only: [:create, :update]
    resources :reviews, except: [:destroy]
  end

  resources :categories, only: [:index, :show]

  resources :reviews, only: [:show, :index] do
    resources :likes, only: [:create]
  end

  resources :search, only: [:index]

  namespace :admin do
    resources :users
    resources :categories
    resources :movies
    resources :movie_categories
    resources :ratings
    resources :reviews
    resources :likes

    root to: "users#index"
  end

end

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <ul class="search-form">
    <li><%= render 'search/form' %></li>
  </ul>

  <ul>
    <li><%= link_to 'Home', root_path %></li>
  </ul>
  <ul>
    <li class="sidebar-title">REVIEWS</li>
    <li><%= link_to 'Recent', movies_recent_path %></li>
    <li><%= link_to 'Top', movies_top_path %></li>
  </ul>
  <ul>
    <li>CATEGORIES</li>
    <% top_categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
  <ul class="user-links">
  <% if current_user && current_user.admin? %>
    <li><a href="#"><%= current_user.name %> (admin)</a></li>
  <% elsif current_user && current_user.critic? %>
    <li><a href="#"><%= current_user.name %> (critic)</a></li>
  <% elsif current_user && current_user.user? %>
    <li><a href="#"><%= current_user.username %></a></li>
  <% else %>
    <li><%= link_to 'Sign In', new_user_session_path %></li>
    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
  <% end %>
  <% if current_user %>
    <li><%= link_to 'Log Out', destroy_user_session_path, :method => 'delete' %></li>
  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FreshCabbage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
</head>
<body>

<input type="checkbox" id="sidebartoggler" name="" value="">

<div class="page-wrap">

  <label for="sidebartoggler" class="toggle">☰</label>

  <div class="page-content">
    <%= yield %>
  </div>

  <%= render partial: "layouts/sidebar" %>
</div>
</body>
</html>